version: "4"
services:
  mysql-db:
    image: mysql
    container_name: mysql-db-orderMicroservice
    environment:
      #Username is not required for the root user
      #     #only the root password simple passowrd is for additional users to the database
      MYSQL_ROOT_PASSWORD: "Mustafa715"
      MYSQL_DATABASE: "orderMicroserviceDatabase"
    ports:
      - "3308:3306"
    #The ports property always takes a list of strings so the reason for hte -
    volumes:
      - ./data/mysql2:/var/lib/mysql
    restart: always


